export enum SystemRoles {
    ADMIN = "ADMIN",
    CLINIC_ADMIN = "CLINIC_ADMIN",
    CLINIC_ATTENDANT = "CLINIC_ATTENDANT",
    CLIENT = "CLIENT",
    CLINIC_DOCTOR = "CLINIC_DOCTOR",
    OPERATIONAL = "OPERATIONAL",
}
