import {
    ThemeBorderRadius,
    ThemeColors,
    ThemeFontSizes,
    ThemeFontWeights,
} from "@/interfaces/styles"
import { DefaultTheme } from "styled-components/native"

export const theme: DefaultTheme = {
    color: {
        [ThemeColors.WHITE]: "#fff",
        [ThemeColors.BLACK]: "#000",
        [ThemeColors.LIGHT_GRAY]: "#dee2e6",
        [ThemeColors.GRAY]: "#adb5bd",
        [ThemeColors.PRIMARY]: "#ff8931",
        [ThemeColors.SECONDARY]: "#ced4da",
        [ThemeColors.TERTIARY]: "#243890",
        [ThemeColors.INFO]: "#0dcaf0",
        [ThemeColors.SUCCESS]: "#198754",
        [ThemeColors.WARNING]: "#ffc107",
        [ThemeColors.DANGER]: "#dc3545",
        [ThemeColors.LIGHT]: "#f8f9fa",
        [ThemeColors.DARK]: "#212529",
        [ThemeColors.LIGHT_DARK]: "#000000aa",
        [ThemeColors.NONE]: "transparent",
    },

    font: {
        size: {
            [ThemeFontSizes.XS]: 12,
            [ThemeFontSizes.SM]: 14,
            [ThemeFontSizes.MD]: 16,
            [ThemeFontSizes.LG]: 18,
            [ThemeFontSizes.XL]: 20,
            [ThemeFontSizes.XXL]: 24,
        },
        weight: {
            [ThemeFontWeights.LIGHT]: "300",
            [ThemeFontWeights.NORMAL]: "400",
            [ThemeFontWeights.MEDIUM]: "500",
            [ThemeFontWeights.SEMIBOLD]: "600",
            [ThemeFontWeights.BOLD]: "700",
        },
    },
    spacing: {
        0: 0,
        1: 4,
        2: 8,
        3: 14,
        4: 22,
        5: 46,
    },
    border: {
        radius: {
            [ThemeBorderRadius.NONE]: 0,
            [ThemeBorderRadius.SM]: 4,
            [ThemeBorderRadius.MD]: 8,
            [ThemeBorderRadius.LG]: 10,
            [ThemeBorderRadius.XL]: 14,
            [ThemeBorderRadius.XXL]: 20,
            [ThemeBorderRadius.PILL]: 9999,
        },
        width: {
            0: 0,
            1: 1.3,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
        },
    },
    gap: {
        0: 0,
        1: 4,
        2: 8,
        3: 16,
        4: 24,
        5: 48,
    },
    col: {
        1: "8.33%",
        2: "16.66%",
        3: "25%",
        4: "33.33%",
        5: "41.66%",
        6: "50%",
        7: "58.33%",
        8: "66.66%",
        9: "75%",
        10: "83.33%",
        11: "91.66%",
        12: "100%",
    },
    width: {
        auto: "auto",
        "25": "25%",
        "50": "50%",
        "75": "75%",
        "100": "100%",
    },
    height: {
        auto: "auto",
        "25": "25%",
        "50": "50%",
        "75": "75%",
        "100": "100%",
    },
    activeOpacity: 0.5,
}
